### ISSUE TITLE
Package vadimdemedes/ink not compatible with React 19

### ISSUE THREAD

**Issue by jsadoski-rockhall** [sst/v2#22]
There is a current issue with `ink` that is breaking support for React 19 (affects Next 15): vadimdemedes/ink#688 

Discussion: https://discord.com/channels/983865673656705025/1318230919579963473

**Comment by QuentinFontenay** [comment]
Hi, I found myself in the same situation so I decided to fork the ink project to upgrade to react 19 and the latest version of react-reconciler in the meantime. I then override the react version of sst + the ink package.
```
"overrides": {
    "sst": {
      "ink": "https://github.com/QuentinFontenay/ink/tree/react-v19.0.0",
      "react": "$react"
    }
  },
```

**Comment by bensleym25** [comment]
IS this issue going to be fixed anytime soon?

**Comment by SteveKekacs** [comment]
Any update on this?

**Comment by arturenault** [comment]
```
Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

Trace: Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:4279:9)
    at reconcileChildFibers (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:5220:7)
    at reconcileChildren (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:10366:28)
    at updateHostRoot (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:11085:5)
    at beginWork (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:12827:14)
    at beginWork$1 (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:19608:14)
    at performUnitOfWork (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:18742:12)
    at workLoopSync (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:18648:5)
    at renderRootSync (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:18616:7)
    at performSyncWorkOnRoot (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:18232:20)
    at flushSyncCallbacks (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:2936:22)
    at flushSyncCallbacksOnlyInLegacyMode (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:2915:5)
    at scheduleUpdateOnFiber (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:17685:7)
    at Object.updateContainer (/home/runner/work/sift/sift/node_modules/.pnpm/react-reconciler@0.29.2_react@18.3.1/node_modules/react-reconciler/cjs/react-reconciler.development.js:21061:5)
    at Ink.render (file:///home/runner/work/sift/sift/node_modules/.pnpm/ink@4.4.1_patch_hash=1a5ad666dfdd8e875e72b55f9fd06037b9fc51db9a9df77fc14156ab89b34738_@_72f2d1c568a3c7b674852a71d034a8c0/node_modules/ink/build/ink.js:226:20)
    at render (file:///home/runner/work/sift/sift/node_modules/.pnpm/ink@4.4.1_patch_hash=1a5ad666dfdd8e875e72b55f9fd06037b9fc51db9a9df77fc14156ab89b34738_@_72f2d1c568a3c7b674852a71d034a8c0/node_modules/ink/build/render.js:19:14)
    at Object.handler (file:///home/runner/work/sift/sift/node_modules/.pnpm/sst@2.43.7_@types+react@19.0.10_aws-crt@1.22.0_bufferutil@4.0.7_utf-8-validate@5.0.10___1635e5773ff54119968b2219ca42650d/node_modules/sst/cli/commands/deploy.js:93:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at process.<anonymous> (file:///home/runner/work/sift/sift/node_modules/.pnpm/sst@2.43.7_@types+react@19.0.10_aws-crt@1.22.0_bufferutil@4.0.7_utf-8-validate@5.0.10___1635e5773ff54119968b2219ca42650d/node_modules/sst/cli/sst.js:58:21)
    at process.emit (node:events:529:35)
    at process.processEmit [as emit] (/home/runner/work/sift/sift/node_modules/.pnpm/signal-exit@3.0.7/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:169:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

```

This is the error we hit in case it helps anyone.

**Comment by berenddeboer** [comment]
The true cause is the peer dependency in ink or react-reconciler. ChatGpt 5 fixed this with introducing these overrides:

```
  "pnpm": {
    "overrides": {
      "sst@2>react": "18.3.1",
      "sst@2>react-dom": "18.3.1",
      "sst@2>@types/react": "18.3.10",
      "ink@4>react": "18.3.1",
      "ink@4>@types/react": "18.3.10",
      "ink@4>react-reconciler": "0.29.2"
    }
  }
```

**Comment by berenddeboer** [comment]
Update on this: this does not seem to "stick" well. After some updates, the error came back. Did:
1. Removed the overrides.
2. `pnpm i`
3. Added the overrides back in.
4. `pnpm i`

Not a great solution....
